-- Hand-curated seed for the Singapore fresh-grad market. Salary figures are
-- SGD fixed monthly for entry-level roles and are deliberately conservative.
-- This is curation, not scraping, and it is the moat. Verify quarterly.

insert into companies (
  name, slug, website, description, industry, company_type, employee_count_range,
  hires_poly_grads, hires_uni_grads, preferred_institutions, required_skills, nice_to_have_skills,
  sponsors_s_pass, sponsors_ep, s_pass_min_salary, visa_notes,
  salary_p25, salary_p50, salary_p75, salary_notes,
  common_entry_roles, typical_hiring_timeline, interview_format, apply_via, data_confidence, tags
) values

-- ━━━ Government and statutory boards (Singapore citizens / PR only) ━━━
(
  'GovTech Singapore', 'govtech', 'https://www.tech.gov.sg',
  'The technology agency for the Singapore government, building citizen-facing digital services.',
  'govtech', 'government', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu','sit'],
  ARRAY['JavaScript','Python','React','Node.js','SQL'],
  ARRAY['TypeScript','Docker','AWS','Kubernetes'],
  false, false, null, 'Singapore government roles are open to citizens and PR only.',
  3200, 3800, 4600, 'Includes 13th month. Annual variable bonus on top.',
  ARRAY['Software Engineer','UX Designer','Data Analyst','Product Manager'],
  '4-8 weeks', '1 HR call + 1 technical + 1 panel interview',
  'company_website', 'high',
  ARRAY['government','stable','good_benefits','citizen_pr_only']
),
(
  'DSTA', 'dsta', 'https://www.dsta.gov.sg',
  'Defence Science and Technology Agency, delivering tech for national defence.',
  'govtech', 'statutory_board', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','sutd'],
  ARRAY['Python','C++','Java','SQL'],
  ARRAY['Machine Learning','Cybersecurity','Cloud'],
  false, false, null, 'Defence-linked roles, citizens and PR only.',
  3300, 4000, 4900, null,
  ARRAY['Software Engineer','Systems Engineer','Cybersecurity Analyst'],
  '6-10 weeks', '1 HR + 1 technical + panel',
  'company_website', 'high',
  ARRAY['government','defence','stable','citizen_pr_only']
),
(
  'DSO National Laboratories', 'dso', 'https://www.dso.org.sg',
  'Singapore primary defence research and development organisation.',
  'govtech', 'statutory_board', '1000+',
  false, true,
  ARRAY['nus','ntu','sutd','smu'],
  ARRAY['Python','C++','Machine Learning','Mathematics'],
  ARRAY['Signal Processing','Research'],
  false, false, null, 'Research roles, citizens and PR only.',
  3500, 4200, 5200, 'Strong for those with research or honours background.',
  ARRAY['Research Engineer','Member of Technical Staff'],
  '8-12 weeks', '1 HR + technical + research panel',
  'company_website', 'medium',
  ARRAY['government','research','defence','citizen_pr_only']
),
(
  'CPF Board', 'cpf-board', 'https://www.cpf.gov.sg',
  'Administers the national social security savings scheme.',
  'govtech', 'statutory_board', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu'],
  ARRAY['SQL','Java','Business Analysis'],
  ARRAY['React','Data Analysis'],
  false, false, null, 'Citizens and PR only.',
  3000, 3600, 4300, null,
  ARRAY['IT Executive','Business Analyst','Data Analyst'],
  '4-8 weeks', '1 HR + 1 panel',
  'company_website', 'medium',
  ARRAY['government','stable','good_benefits','citizen_pr_only']
),
(
  'NParks ITO', 'nparks-ito', 'https://www.nparks.gov.sg',
  'IT office of the National Parks Board.',
  'govtech', 'statutory_board', '201-1000',
  true, true,
  ARRAY['tp','sp','np','nyp'],
  ARRAY['SQL','GIS','JavaScript'],
  ARRAY['Python','Data Visualisation'],
  false, false, null, 'Citizens and PR only.',
  2900, 3400, 4000, null,
  ARRAY['IT Executive','GIS Analyst'],
  '4-8 weeks', '1 HR + 1 panel',
  'company_website', 'low',
  ARRAY['government','stable','citizen_pr_only']
),
(
  'MOH Holdings', 'moh-holdings', 'https://www.mohh.com.sg',
  'Holding company for Singapore public healthcare clusters.',
  'healthtech', 'statutory_board', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu'],
  ARRAY['SQL','Java','Healthcare IT'],
  ARRAY['Data Analysis','Epic'],
  false, false, null, 'Citizens and PR only.',
  3100, 3700, 4400, null,
  ARRAY['IT Analyst','Software Engineer','Data Analyst'],
  '6-10 weeks', '1 HR + 1 technical + panel',
  'company_website', 'medium',
  ARRAY['government','healthcare','stable','citizen_pr_only']
),
(
  'HDB IT', 'hdb-it', 'https://www.hdb.gov.sg',
  'Information technology division of the Housing and Development Board.',
  'govtech', 'statutory_board', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu'],
  ARRAY['Java','SQL','JavaScript'],
  ARRAY['React','Cloud'],
  false, false, null, 'Citizens and PR only.',
  3000, 3600, 4300, null,
  ARRAY['IT Executive','Software Engineer'],
  '4-8 weeks', '1 HR + 1 technical + panel',
  'company_website', 'low',
  ARRAY['government','stable','citizen_pr_only']
),
(
  'LTA IT', 'lta-it', 'https://www.lta.gov.sg',
  'Technology division of the Land Transport Authority.',
  'govtech', 'statutory_board', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu'],
  ARRAY['Java','SQL','Systems'],
  ARRAY['IoT','Data Analysis'],
  false, false, null, 'Citizens and PR only.',
  3000, 3600, 4400, null,
  ARRAY['IT Executive','Systems Analyst'],
  '4-8 weeks', '1 HR + 1 panel',
  'company_website', 'low',
  ARRAY['government','transport','stable','citizen_pr_only']
),
(
  'IRAS IT', 'iras-it', 'https://www.iras.gov.sg',
  'Technology division of the Inland Revenue Authority of Singapore.',
  'govtech', 'statutory_board', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu'],
  ARRAY['SQL','Java','Business Analysis'],
  ARRAY['Data Analytics','SAP'],
  false, false, null, 'Citizens and PR only.',
  3100, 3700, 4400, null,
  ARRAY['IT Executive','Business Analyst','Data Analyst'],
  '4-8 weeks', '1 HR + 1 panel',
  'company_website', 'low',
  ARRAY['government','stable','citizen_pr_only']
),
(
  'MAS Technology', 'mas-technology', 'https://www.mas.gov.sg',
  'Technology group of the Monetary Authority of Singapore.',
  'fintech', 'statutory_board', '1000+',
  false, true,
  ARRAY['nus','ntu','smu','sit'],
  ARRAY['Java','Python','SQL','Cloud'],
  ARRAY['Machine Learning','Cybersecurity'],
  false, false, null, 'Citizens and PR only.',
  3600, 4300, 5200, 'Among the higher-paying public sector tech roles.',
  ARRAY['Technology Analyst','Data Scientist','Cybersecurity Specialist'],
  '6-10 weeks', '1 HR + technical + panel',
  'company_website', 'medium',
  ARRAY['government','fintech','prestige','citizen_pr_only']
),

-- ━━━ Local banks, technology teams ━━━
(
  'DBS Bank', 'dbs', 'https://www.dbs.com',
  'The largest bank in Southeast Asia, with a large in-house technology org.',
  'fintech', 'mnc', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu','sit'],
  ARRAY['Java','Python','SQL','React'],
  ARRAY['Spring Boot','AWS','Kafka','Angular'],
  true, true, 3150, 'Sponsors S Pass and EP for technology roles.',
  3400, 4200, 5200, 'SEED graduate programme and direct hires both available.',
  ARRAY['Software Engineer','Data Analyst','Technology Analyst'],
  '4-8 weeks', '1 HR + coding assessment + 1-2 technical + hiring manager',
  'company_website', 'high',
  ARRAY['bank','stable','graduate_programme','sponsors_visa']
),
(
  'OCBC Bank', 'ocbc', 'https://www.ocbc.com',
  'One of Singapore three local banks, with a growing engineering team.',
  'fintech', 'mnc', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu'],
  ARRAY['Java','SQL','Python'],
  ARRAY['Spring Boot','React','Cloud'],
  true, true, 3150, 'Sponsors S Pass and EP for technology and analytics roles.',
  3300, 4000, 4900, null,
  ARRAY['Software Engineer','Business Analyst','Data Analyst'],
  '4-8 weeks', '1 HR + technical + hiring manager',
  'company_website', 'high',
  ARRAY['bank','stable','graduate_programme','sponsors_visa']
),
(
  'UOB', 'uob', 'https://www.uobgroup.com',
  'United Overseas Bank, with regional technology hubs in Singapore.',
  'fintech', 'mnc', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu'],
  ARRAY['Java','SQL','Python'],
  ARRAY['Angular','Cloud','DevOps'],
  true, true, 3150, 'Sponsors S Pass and EP for technology roles.',
  3300, 4000, 4800, null,
  ARRAY['Software Engineer','Technology Analyst','Data Analyst'],
  '4-8 weeks', '1 HR + technical + hiring manager',
  'company_website', 'high',
  ARRAY['bank','stable','sponsors_visa']
),
(
  'Standard Chartered Singapore', 'standard-chartered', 'https://www.sc.com',
  'Global bank with a major technology and innovation presence in Singapore.',
  'fintech', 'mnc', '1000+',
  true, true,
  ARRAY['tp','sp','np','nus','ntu','smu','sit'],
  ARRAY['Java','Python','SQL','Cloud'],
  ARRAY['Kubernetes','React','Kafka'],
  true, true, 3150, 'Sponsors S Pass and EP for technology roles.',
  3400, 4200, 5100, null,
  ARRAY['Software Engineer','Technology Analyst','Data Engineer'],
  '5-9 weeks', '1 HR + coding assessment + technical + hiring manager',
  'company_website', 'high',
  ARRAY['bank','global','sponsors_visa']
),
(
  'Citibank Singapore', 'citibank', 'https://www.citigroup.com',
  'US global bank with a large Singapore technology centre.',
  'fintech', 'mnc', '1000+',
  false, true,
  ARRAY['nus','ntu','smu','sit'],
  ARRAY['Java','Python','SQL'],
  ARRAY['Spring Boot','Cloud','React'],
  true, true, 3150, 'Sponsors S Pass and EP, mostly favours university grads for analyst tracks.',
  3500, 4400, 5400, null,
  ARRAY['Technology Analyst','Software Engineer'],
  '5-9 weeks', '1 HR + online assessment + technical + hiring manager',
  'company_website', 'medium',
  ARRAY['bank','global','sponsors_visa','uni_leaning']
),

-- ━━━ E-commerce and regional tech ━━━
(
  'Shopee', 'shopee', 'https://careers.shopee.sg',
  'Leading e-commerce platform in Southeast Asia, part of Sea Group.',
  'ecommerce', 'scaleup', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu','sit'],
  ARRAY['Java','Go','Python','SQL','React'],
  ARRAY['MySQL','Redis','Kafka','TypeScript'],
  true, true, 3150, 'Sponsors S Pass and EP for engineering roles.',
  3200, 4000, 4800, 'Large fresh-grad intake, fast-moving environment.',
  ARRAY['Software Engineer','Backend Developer','Data Analyst','Product Operations'],
  '3-5 weeks', '1 HR + online coding test + 1-2 technical + hiring manager',
  'company_website', 'high',
  ARRAY['ecommerce','high_intake','fast_paced','sponsors_visa']
),
(
  'Grab', 'grab', 'https://grab.careers',
  'Southeast Asia super-app spanning ride-hailing, deliveries and payments.',
  'ecommerce', 'scaleup', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu','sit'],
  ARRAY['Go','Java','Python','SQL'],
  ARRAY['Kubernetes','AWS','React','TypeScript'],
  true, true, 3150, 'Sponsors S Pass and EP for engineering and data roles.',
  3400, 4200, 5200, null,
  ARRAY['Software Engineer','Data Analyst','Data Engineer','Product Analyst'],
  '4-6 weeks', '1 HR + coding test + 2 technical + hiring manager',
  'company_website', 'high',
  ARRAY['ecommerce','super_app','sponsors_visa']
),
(
  'Lazada', 'lazada', 'https://www.lazada.com',
  'Major Southeast Asian e-commerce platform backed by Alibaba.',
  'ecommerce', 'scaleup', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu'],
  ARRAY['Java','Python','SQL','React'],
  ARRAY['Spring Boot','Alibaba Cloud','Vue'],
  true, true, 3150, 'Sponsors S Pass and EP for tech roles.',
  3100, 3900, 4700, null,
  ARRAY['Software Engineer','Data Analyst','Business Analyst'],
  '3-6 weeks', '1 HR + technical + hiring manager',
  'company_website', 'medium',
  ARRAY['ecommerce','sponsors_visa']
),
(
  'Sea Group', 'sea-group', 'https://career.sea.com',
  'Parent company of Shopee, Garena and SeaMoney.',
  'gaming', 'scaleup', '1000+',
  true, true,
  ARRAY['tp','sp','np','nus','ntu','smu','sit'],
  ARRAY['Java','Go','Python','SQL'],
  ARRAY['C++','Kafka','React'],
  true, true, 3150, 'Sponsors S Pass and EP for engineering roles.',
  3300, 4100, 5000, null,
  ARRAY['Software Engineer','Backend Developer','Game Developer'],
  '4-6 weeks', '1 HR + coding test + technical + hiring manager',
  'company_website', 'medium',
  ARRAY['gaming','ecommerce','sponsors_visa']
),
(
  'Carousell', 'carousell', 'https://careers.carousell.com',
  'Singapore-born classifieds and recommerce marketplace.',
  'ecommerce', 'scaleup', '201-1000',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu'],
  ARRAY['Python','Java','React','SQL'],
  ARRAY['Kotlin','Swift','GraphQL'],
  true, true, 3150, 'Sponsors S Pass and EP for engineering roles.',
  3200, 3900, 4700, null,
  ARRAY['Software Engineer','Mobile Developer','Data Analyst'],
  '3-5 weeks', '1 HR + technical + hiring manager',
  'company_website', 'medium',
  ARRAY['ecommerce','local_unicorn','sponsors_visa']
),
(
  'Ninja Van', 'ninja-van', 'https://www.ninjavan.co',
  'Tech-enabled last-mile logistics across Southeast Asia.',
  'logistics', 'scaleup', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu'],
  ARRAY['Java','Python','SQL','React'],
  ARRAY['Spring Boot','AWS','Kafka'],
  true, true, 3150, 'Sponsors S Pass and EP for tech roles.',
  3000, 3700, 4500, null,
  ARRAY['Software Engineer','Data Analyst','Operations Analyst'],
  '3-5 weeks', '1 HR + technical + hiring manager',
  'company_website', 'medium',
  ARRAY['logistics','sponsors_visa']
),
(
  'foodpanda Singapore', 'foodpanda', 'https://www.foodpanda.com',
  'On-demand food and grocery delivery, part of Delivery Hero.',
  'ecommerce', 'scaleup', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu'],
  ARRAY['Python','SQL','JavaScript'],
  ARRAY['React','Data Analysis','Tableau'],
  true, true, 3150, 'Sponsors S Pass and EP for tech and analytics roles.',
  3000, 3700, 4500, null,
  ARRAY['Data Analyst','Software Engineer','Operations Analyst'],
  '3-5 weeks', '1 HR + case study + hiring manager',
  'company_website', 'medium',
  ARRAY['ecommerce','delivery','sponsors_visa']
),

-- ━━━ MNC engineering offices ━━━
(
  'ByteDance Singapore', 'bytedance', 'https://jobs.bytedance.com',
  'Parent company of TikTok, with a major engineering hub in Singapore.',
  'saas', 'mnc', '1000+',
  false, true,
  ARRAY['nus','ntu','smu','sit'],
  ARRAY['Go','Python','C++','SQL'],
  ARRAY['Machine Learning','Kubernetes','React'],
  true, true, 3500, 'Sponsors S Pass and EP, strong preference for university grads.',
  4500, 5500, 6800, 'Among the highest fresh-grad tech pay in Singapore.',
  ARRAY['Software Engineer','Data Scientist','Machine Learning Engineer'],
  '4-7 weeks', '2-3 technical rounds + hiring manager',
  'company_website', 'high',
  ARRAY['bigtech','high_pay','competitive','sponsors_visa','uni_leaning']
),
(
  'TikTok Singapore', 'tiktok', 'https://careers.tiktok.com',
  'Short-form video platform, with regional HQ functions in Singapore.',
  'saas', 'mnc', '1000+',
  false, true,
  ARRAY['nus','ntu','smu','sit'],
  ARRAY['Go','Python','SQL','React'],
  ARRAY['Machine Learning','TypeScript','Kubernetes'],
  true, true, 3500, 'Sponsors S Pass and EP, strong preference for university grads.',
  4300, 5300, 6600, null,
  ARRAY['Software Engineer','Data Analyst','Product Operations'],
  '4-7 weeks', '2-3 technical rounds + hiring manager',
  'company_website', 'high',
  ARRAY['bigtech','high_pay','competitive','sponsors_visa','uni_leaning']
),
(
  'Stripe Singapore', 'stripe', 'https://stripe.com/jobs',
  'Global payments infrastructure company with an APAC hub in Singapore.',
  'fintech', 'mnc', '201-1000',
  false, true,
  ARRAY['nus','ntu','smu','sutd'],
  ARRAY['Ruby','Java','Go','SQL'],
  ARRAY['Distributed Systems','React','API Design'],
  true, true, 3500, 'Sponsors EP, very selective hiring.',
  5000, 6000, 7200, null,
  ARRAY['Software Engineer','Solutions Engineer'],
  '5-8 weeks', '1 recruiter + 3-4 technical rounds',
  'company_website', 'medium',
  ARRAY['bigtech','high_pay','competitive','sponsors_visa','uni_leaning']
),
(
  'Salesforce Singapore', 'salesforce', 'https://careers.salesforce.com',
  'Global enterprise CRM and cloud software company.',
  'saas', 'mnc', '1000+',
  false, true,
  ARRAY['nus','ntu','smu','sit'],
  ARRAY['Java','JavaScript','SQL'],
  ARRAY['Apex','Lightning','Cloud'],
  true, true, 3500, 'Sponsors EP for engineering roles.',
  4200, 5000, 6000, null,
  ARRAY['Software Engineer','Solution Engineer','Technical Consultant'],
  '5-8 weeks', '1 recruiter + technical + panel',
  'company_website', 'medium',
  ARRAY['enterprise','high_pay','sponsors_visa','uni_leaning']
),
(
  'Microsoft Singapore', 'microsoft', 'https://careers.microsoft.com',
  'Global software and cloud company with engineering and sales in Singapore.',
  'saas', 'mnc', '1000+',
  false, true,
  ARRAY['nus','ntu','smu','sutd','sit'],
  ARRAY['C#','Java','Python','SQL'],
  ARRAY['Azure','React','TypeScript'],
  true, true, 3500, 'Sponsors EP for engineering roles.',
  4500, 5400, 6500, null,
  ARRAY['Software Engineer','Cloud Solution Architect','Data Analyst'],
  '5-9 weeks', '1 recruiter + 3-4 interviews',
  'company_website', 'medium',
  ARRAY['bigtech','high_pay','sponsors_visa','uni_leaning']
),
(
  'Google Singapore', 'google', 'https://careers.google.com',
  'Global technology company with APAC functions based in Singapore.',
  'saas', 'mnc', '1000+',
  false, true,
  ARRAY['nus','ntu','smu','sutd'],
  ARRAY['C++','Java','Python','Go'],
  ARRAY['Data Structures','Algorithms','Distributed Systems'],
  true, true, 3500, 'Sponsors EP, extremely competitive.',
  5200, 6300, 7500, null,
  ARRAY['Software Engineer','Data Scientist'],
  '6-10 weeks', 'Recruiter + phone screen + 4-5 onsite rounds',
  'company_website', 'medium',
  ARRAY['bigtech','high_pay','competitive','sponsors_visa','uni_leaning']
),
(
  'Amazon Singapore', 'amazon', 'https://www.amazon.jobs',
  'Global e-commerce and cloud company with engineering teams in Singapore.',
  'saas', 'mnc', '1000+',
  false, true,
  ARRAY['nus','ntu','smu','sit','sutd'],
  ARRAY['Java','Python','SQL'],
  ARRAY['AWS','Data Structures','System Design'],
  true, true, 3500, 'Sponsors EP for engineering roles.',
  4500, 5400, 6500, null,
  ARRAY['Software Development Engineer','Business Analyst','Data Engineer'],
  '5-9 weeks', '1 recruiter + online assessment + 4-5 loop interviews',
  'company_website', 'medium',
  ARRAY['bigtech','high_pay','sponsors_visa','uni_leaning']
),

-- ━━━ Singapore SMEs and startups ━━━
(
  'Circles.Life', 'circles-life', 'https://www.circles.life',
  'Singapore digital telco and SaaS platform builder.',
  'saas', 'startup', '201-1000',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu'],
  ARRAY['JavaScript','React','Node.js','SQL'],
  ARRAY['TypeScript','AWS','Python'],
  true, true, 3150, 'Sponsors S Pass and EP for tech roles.',
  3200, 3900, 4700, null,
  ARRAY['Software Engineer','Data Analyst','Product Analyst'],
  '3-5 weeks', '1 HR + technical + hiring manager',
  'company_website', 'medium',
  ARRAY['startup','telco','sponsors_visa']
),
(
  'Endowus', 'endowus', 'https://endowus.com',
  'Digital wealth platform for CPF, SRS and cash investing.',
  'fintech', 'startup', '51-200',
  true, true,
  ARRAY['tp','sp','np','nus','ntu','smu'],
  ARRAY['JavaScript','React','Node.js','SQL'],
  ARRAY['TypeScript','GraphQL','AWS'],
  true, true, 3150, 'Sponsors S Pass and EP for engineering roles.',
  3300, 4000, 4900, null,
  ARRAY['Software Engineer','Product Analyst','Data Analyst'],
  '3-5 weeks', '1 HR + technical + founder or lead',
  'company_website', 'medium',
  ARRAY['fintech','wealthtech','startup','sponsors_visa']
),
(
  'Syfe', 'syfe', 'https://www.syfe.com',
  'Digital investment platform for the retail market in Asia.',
  'fintech', 'startup', '51-200',
  true, true,
  ARRAY['tp','sp','np','nus','ntu'],
  ARRAY['JavaScript','React','Python','SQL'],
  ARRAY['Node.js','AWS','Kotlin'],
  true, true, 3150, 'Sponsors S Pass and EP for engineering roles.',
  3200, 3900, 4700, null,
  ARRAY['Software Engineer','Mobile Developer','Data Analyst'],
  '3-5 weeks', '1 HR + technical + hiring manager',
  'company_website', 'low',
  ARRAY['fintech','wealthtech','startup','sponsors_visa']
),
(
  'StashAway', 'stashaway', 'https://www.stashaway.sg',
  'Digital wealth manager operating across Asia and the Middle East.',
  'fintech', 'startup', '201-1000',
  true, true,
  ARRAY['tp','sp','np','nus','ntu','smu'],
  ARRAY['JavaScript','React','Python','SQL'],
  ARRAY['TypeScript','Node.js','AWS'],
  true, true, 3150, 'Sponsors S Pass and EP for engineering roles.',
  3300, 4000, 4900, null,
  ARRAY['Software Engineer','Data Analyst','Product Analyst'],
  '3-5 weeks', '1 HR + technical + hiring manager',
  'company_website', 'medium',
  ARRAY['fintech','wealthtech','startup','sponsors_visa']
),
(
  'Vouch', 'vouch', 'https://www.vouchhq.io',
  'Singapore hospitality and guest-experience software startup.',
  'saas', 'startup', '11-50',
  true, true,
  ARRAY['tp','sp','np','nyp'],
  ARRAY['JavaScript','React','Node.js'],
  ARRAY['TypeScript','SQL','AWS'],
  true, false, 3150, 'May sponsor S Pass for engineering roles, confirm during interview.',
  3000, 3600, 4300, null,
  ARRAY['Software Engineer','Frontend Developer'],
  '2-4 weeks', '1 founder chat + technical',
  'company_website', 'low',
  ARRAY['startup','small_team','poly_friendly']
),
(
  'PatSnap', 'patsnap', 'https://www.patsnap.com',
  'Innovation intelligence platform born in Singapore.',
  'saas', 'scaleup', '201-1000',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu'],
  ARRAY['Java','Python','React','SQL'],
  ARRAY['Machine Learning','Elasticsearch','AWS'],
  true, true, 3150, 'Sponsors S Pass and EP for engineering roles.',
  3200, 3900, 4700, null,
  ARRAY['Software Engineer','Data Analyst','NLP Engineer'],
  '3-5 weeks', '1 HR + technical + hiring manager',
  'company_website', 'medium',
  ARRAY['saas','startup','sponsors_visa']
),

-- ━━━ Consulting and IT services ━━━
(
  'NCS Group', 'ncs', 'https://www.ncs.co',
  'Large Singapore IT services and consulting firm, part of Singtel.',
  'consulting', 'mnc', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu','sit'],
  ARRAY['Java','SQL','JavaScript'],
  ARRAY['React','Cloud','SAP'],
  true, true, 3150, 'Sponsors S Pass and EP, very poly-friendly with a structured grad track.',
  3000, 3500, 4200, 'High intake, good first job for poly grads building enterprise experience.',
  ARRAY['Associate Software Engineer','Systems Analyst','Business Analyst'],
  '3-6 weeks', '1 HR + technical + hiring manager',
  'company_website', 'high',
  ARRAY['consulting','high_intake','poly_friendly','sponsors_visa','graduate_programme']
),
(
  'Accenture Singapore', 'accenture', 'https://www.accenture.com',
  'Global professional services firm with a large Singapore technology practice.',
  'consulting', 'mnc', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu','sit'],
  ARRAY['Java','SQL','JavaScript'],
  ARRAY['SAP','Salesforce','Cloud'],
  true, true, 3150, 'Sponsors S Pass and EP, large fresh-grad intake.',
  3100, 3700, 4500, null,
  ARRAY['Application Developer','Technology Analyst','Business Analyst'],
  '3-6 weeks', '1 HR + online assessment + interview',
  'company_website', 'high',
  ARRAY['consulting','high_intake','poly_friendly','sponsors_visa']
),
(
  'Thoughtworks Singapore', 'thoughtworks', 'https://www.thoughtworks.com',
  'Global software consultancy known for engineering craft.',
  'consulting', 'mnc', '201-1000',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu','sit'],
  ARRAY['Java','Python','JavaScript','SQL'],
  ARRAY['TDD','Agile','React','Cloud'],
  true, true, 3150, 'Sponsors S Pass and EP, values portfolio over pedigree.',
  3400, 4100, 5000, 'Strong fit for poly grads with a solid GitHub portfolio.',
  ARRAY['Graduate Developer','Software Engineer'],
  '4-7 weeks', '1 HR + logic test + pair-programming + interview',
  'company_website', 'high',
  ARRAY['consulting','craft','portfolio_friendly','poly_friendly','sponsors_visa']
),
(
  'IBM Singapore', 'ibm', 'https://www.ibm.com/careers',
  'Global technology and consulting company.',
  'consulting', 'mnc', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu','smu'],
  ARRAY['Java','Python','SQL'],
  ARRAY['Cloud','AI','Red Hat'],
  true, true, 3150, 'Sponsors S Pass and EP for tech roles.',
  3100, 3700, 4500, null,
  ARRAY['Software Engineer','Technology Consultant','Data Analyst'],
  '4-7 weeks', '1 HR + technical + panel',
  'company_website', 'medium',
  ARRAY['consulting','enterprise','sponsors_visa']
),
(
  'Infosys Singapore', 'infosys', 'https://www.infosys.com',
  'Global IT services and consulting company.',
  'consulting', 'mnc', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu'],
  ARRAY['Java','SQL','JavaScript'],
  ARRAY['Cloud','SAP','Testing'],
  true, true, 3150, 'Sponsors S Pass and EP, high intake of fresh grads.',
  2800, 3300, 4000, null,
  ARRAY['Systems Engineer','Software Engineer','Test Analyst'],
  '3-6 weeks', '1 HR + technical + interview',
  'company_website', 'medium',
  ARRAY['consulting','high_intake','sponsors_visa']
),
(
  'TCS Singapore', 'tcs', 'https://www.tcs.com',
  'Tata Consultancy Services, a large global IT services firm.',
  'consulting', 'mnc', '1000+',
  true, true,
  ARRAY['tp','sp','np','nyp','nus','ntu'],
  ARRAY['Java','SQL','JavaScript'],
  ARRAY['Cloud','SAP','Testing'],
  true, true, 3150, 'Sponsors S Pass and EP, high intake of fresh grads.',
  2800, 3300, 4000, null,
  ARRAY['Systems Engineer','Software Engineer','Business Analyst'],
  '3-6 weeks', '1 HR + technical + interview',
  'company_website', 'medium',
  ARRAY['consulting','high_intake','sponsors_visa']
),

-- ━━━ Fintech ━━━
(
  'Wise Singapore', 'wise', 'https://www.wise.jobs',
  'Global money transfer company with an APAC hub in Singapore.',
  'fintech', 'scaleup', '201-1000',
  false, true,
  ARRAY['nus','ntu','smu','sutd'],
  ARRAY['Java','JavaScript','SQL','React'],
  ARRAY['Kotlin','AWS','TypeScript'],
  true, true, 3500, 'Sponsors S Pass and EP, leans toward university grads.',
  4000, 4800, 5800, null,
  ARRAY['Software Engineer','Product Analyst'],
  '4-7 weeks', '1 recruiter + technical + values interview',
  'company_website', 'medium',
  ARRAY['fintech','high_pay','sponsors_visa','uni_leaning']
),
(
  'Nium', 'nium', 'https://www.nium.com',
  'Global B2B payments and embedded finance company born in Singapore.',
  'fintech', 'scaleup', '201-1000',
  true, true,
  ARRAY['tp','sp','np','nus','ntu','smu'],
  ARRAY['Java','Python','SQL','React'],
  ARRAY['Spring Boot','AWS','Microservices'],
  true, true, 3150, 'Sponsors S Pass and EP for engineering roles.',
  3300, 4000, 4900, null,
  ARRAY['Software Engineer','Data Analyst','QA Engineer'],
  '3-6 weeks', '1 HR + technical + hiring manager',
  'company_website', 'medium',
  ARRAY['fintech','payments','sponsors_visa']
),
(
  'Aspire', 'aspire', 'https://aspireapp.com',
  'All-in-one finance platform for businesses across Southeast Asia.',
  'fintech', 'startup', '201-1000',
  true, true,
  ARRAY['tp','sp','np','nus','ntu'],
  ARRAY['JavaScript','React','Node.js','SQL'],
  ARRAY['TypeScript','Go','AWS'],
  true, true, 3150, 'Sponsors S Pass and EP for engineering roles.',
  3300, 4000, 4900, null,
  ARRAY['Software Engineer','Frontend Developer','Data Analyst'],
  '3-5 weeks', '1 HR + technical + hiring manager',
  'company_website', 'medium',
  ARRAY['fintech','startup','sponsors_visa']
),
(
  'Validus', 'validus', 'https://validus.sg',
  'SME financing and digital lending platform in Southeast Asia.',
  'fintech', 'startup', '51-200',
  true, true,
  ARRAY['tp','sp','np','nus','ntu'],
  ARRAY['Java','JavaScript','SQL'],
  ARRAY['React','Spring Boot','AWS'],
  true, false, 3150, 'May sponsor S Pass for engineering roles, confirm during interview.',
  3100, 3700, 4500, null,
  ARRAY['Software Engineer','Data Analyst'],
  '3-5 weeks', '1 HR + technical + hiring manager',
  'company_website', 'low',
  ARRAY['fintech','lending','startup']
),
(
  'Funding Societies', 'funding-societies', 'https://fundingsocieties.com',
  'Largest SME digital financing platform in Southeast Asia.',
  'fintech', 'scaleup', '201-1000',
  true, true,
  ARRAY['tp','sp','np','nus','ntu','smu'],
  ARRAY['Java','Python','SQL','React'],
  ARRAY['Spring Boot','AWS','Kotlin'],
  true, true, 3150, 'Sponsors S Pass and EP for engineering roles.',
  3200, 3900, 4700, null,
  ARRAY['Software Engineer','Data Analyst','Risk Analyst'],
  '3-6 weeks', '1 HR + technical + hiring manager',
  'company_website', 'medium',
  ARRAY['fintech','lending','sponsors_visa']
);
